// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tshzerjeugqaqgzbzumb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzaHplcmpldWdxYXFnemJ6dW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDk5OTAsImV4cCI6MjA2NjgyNTk5MH0.4tlHfFtCth6TF7UYs5w_lUqSIT2GOkSc7g1Jp6N11Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});